In [7]:
#Import the pandas, NumPy, and os libraries.
import pandas as pd
import numpy as np
import os

In [9]:
#Creating a path
path = r'C:\Users\canam\Achievement 4\Instacart Basket Analysis'

In [11]:
#importing ords_prods_merge dataframe
df_ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_derived.pkl'))

MemoryError:

In [7]:
df_ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,first_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,0,20,0,both,Mid-range product,Busiest day,Busiest days,Average Orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,1,10,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,0,11,1,both,Mid-range product,Least busy,Slowest days,Average Orders

In [11]:
df_ords_prods_merge.sort_values("user_id")

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,first_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
6002731,10326,Organic Fuji Apples,24,4,2.7,431534,1,5,4,15,28.0,0,5,0,both,Low-range product,Least busy,Slowest days,Most Orders
92374,196,Soda,77,7,9.0,550135,1,7,1,9,20.0,0,1,1,both,Mid-range product,Regularly busy,Busiest days,Most Orders
92373,196,Soda,77,7,9.0,3367565,1,6,2,7,19.0,0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders
92371,196,Soda,77,7,9.0,2254736,1,4,4,7,29.0,0,1,1,both,Mid-range product,Least busy,Slowest days,Average Orders
92370,196,Soda,77,7,9.0,473747,1,3,3,12,21.0,0,1,1,both,Mid-range product,Regularly busy,Slowest days,Most Orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21518543,33129,Classic Hummus,67,20,1.3,626363,206209,12,1,12,18.0,0,9,1,both,Low-range product,Regularly busy,Busiest days,Most Orders
12350504,20842,Total 0% Greek Yogurt,120,16,13.6,3154581,206209,1,3,11,NaN,1,11,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders
26342158,40992,Chopped Tomatoes,81,15,1.8,2129269,206209,8,3,17,22.0,0,9,1,both,Low-range product,Regularly busy,Slowest days,Average Orders
26025010,40534,In Rich Tomato Sauce Vegetarian Beans,59,15,13.3,3154581,206209,1,3,11,NaN,1,6,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders
14855822,23892,Original High Efficiency Liquid Laundry Detergent,75,17,9.1,688306,206209,4,1,10,30.0,0,16,1,both,Mid-range product,Regularly busy,Busiest days,Most Orders